name: Run Cypress Tests

on:
  schedule:
    # Configura la ejecución para que sea cada semana (domingo a la medianoche UTC)
    - cron: '0 0 * * 0'
  workflow_dispatch: # Permite ejecutar manualmente el workflow desde la interfaz de GitHub

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # O la versión de Node.js que uses en tu proyecto

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run

    - name: Archive Cypress test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: cypress/videos/
    
    - name: Archive screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots
        path: cypress/screenshots/
