name: Cypress Tests for https://travelmapgenerator.com/

on:
  schedule:
    - cron: '0 0 * * 0' # Ejecutar semanalmente a medianoche los domingos
  workflow_dispatch: # Permitir ejecución manual del workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set execute permissions for Cypress
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress tests
        run: npx cypress run

      - name: Archive Cypress test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results

      - name: Archive screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots